### ISSUE TITLE
When using Cyr encryption method, an exception occurs

### ISSUE THREAD

**Issue by anttijuu** [mbuet2ner/JEasyCrypto#1]
Cyr method does not work well, there is an exception in the client side:

```
Welcome to CryptoClient!
Select command (1-4):
 1: Send capability request to service
 2: Send encrypt request to service
 3: Send decrypt request to service
 4: Quit application
Your choice > Response received.
Received raw data: {"result":0,"data":"ѓсфцЀсѓфцсѓфцЀсѓфц","id":1,"operation":"
Parsing...
Unexpected token END OF FILE at position 60.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
	at ResponseReader.run(ResponseReader.java:33)
Starting to receive responses...
```
So there is something wrong in how Cyr method works

**Comment by tvuolio** [comment]
@jennitormala Is your comment in a wrong issue?

**Comment by sakkoja** [comment]
Our group will handle this.

**Comment by mbuet2ner** [comment]
For future PRs please refer to this discussion #35 .
