### ISSUE TITLE
Using non-ascii chars in text to be encrypted fails

### ISSUE THREAD

**Issue by anttijuu** [mbuet2ner/JEasyCrypto#2]
When I try to encrypt Scandinavian chars, this is what I get in the client side:

```
Give encryption method > matrix
Give text to encrypt > ääni kökkö kasa
Welcome to CryptoClient!
Select command (1-4):
 1: Send capability request to service
 2: Send encrypt request to service
 3: Send decrypt request to service
 4: Quit application
Your choice > Response received.
Received raw data: {"result":1,"data":null,"id":1,"operation":"encrypt-response"}
```

So server returns null as encrypted text. And in the server side there is an error you can see in the console:

```
Start to receive packets...
Packet received!
Sender is: 127.0.0.1:10001
Received raw data: {"method":"matrix","data":"ääni kökkö kasa","id":2,"operation":"encry
Parsing...
Unexpected token END OF FILE at position 69.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
	at CryptoServer.run(CryptoServer.java:49)
	at CryptoServer.main(CryptoServer.java:22)
Sending response: {"result":1,"data":null,"id":1,"operation":"encrypt-response"}
```

So the system cannot handle Scandinavian (non-ascii) characters.

**Comment by jennitormala** [comment]
Our group is going to work on this issue.

**Comment by mbuet2ner** [comment]
For future PRs please refer to this discussion #35 .
